runtime: python310  # o la versión de Python que estés utilizando

instance_class: F2

env_variables:
  DASH_DEBUG: 'False'

handlers:
- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT main:app
