<<<<<<< HEAD
runtime: python310  # o la versión de Python que estés utilizando

instance_class: F2

env_variables:
  DASH_DEBUG: 'False'

handlers:
- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT main:app
=======
runtime: python39
entrypoint: gunicorn -b :$PORT main:server
env_variables:
  DASH_DEBUG_MODE: "True"
>>>>>>> 395d25e6ddfb36ad1de89fc3a61d464efb53355c
